#' takes a json formatted list of works associated with a host venue and outputs a data.table of simple citation information
#'
#' @description takes a json work returned by an openAlex query and returns a 1 by X data.table of citation information
#' @param work a work output generated by extractWorks.R
#' @return a data.table object with one work per row
#' @export
#' @importFrom methods is
#' @import data.table
#' @param data_style options for how much/how little data to return, see @details
#' @details Note that because extracted records can be pretty large--and are complicated, nested json file--there is an optional "data_style" command that lets the user specify what to return. Currently there are three options: (1) bare_bones returns OpenAlex ID + DOI, basically, results that can be used to look up the work again; (2) citation returns typical citation information, like journal name, author, etc., with a couple bonus items like source.id to link back to openAlex (3) comprehensive returns author institutional affiliations, open access info, funding data, etc.; and (4) all returns the entire result in original json format.

processWork <- function(work = NULL,data_style = c('citation')){
  dt <- data.table()
  bare_bones <- c('id','doi')
  citation <- c(bare_bones,'author.display_name','publication_year','display_name','source.display_name','source.id','volume','issue','first_page','last_page')
  comprehensive <- c(citation,'is_oa','source.is_oa','author.institutions.id','author.institutions.type','author.institutions.country_code','type','cited_by_count','grants.funder.id','grants.funder_display_name','source.issn_l')
  all <- NULL
  if(data_style=='all'){stop('returning all data as flat file currently not supported, please select another style')}
  if(data_style=='bare_bones'){return(as.data.table(work[c('id','doi')]))}
  if(data_style!='bare_bones'){
    base_info <- as.data.table(work[c('id','doi','title','publication_year','type','cited_by_count')])
    bib_info <- as.data.table(work$biblio)
    open_access <- data.table(is_oa = work$open_access$is_oa,oa_status = work$open_access$oa_status)
    source_info <- parseLocationObject(work)
    author_table <- parseAuthorsObject(work)
    if(nrow(author_table)>0){author_table$author_id <- basename(author_table$author_id)}
    author_collapse <- author_table[,lapply(.SD,paste,collapse = ';'),.SDcols = names(author_table)]
    author_collapse$n_authors <- nrow(author_table)
    grant_table <- parseGrantsObject(work)
    if(nrow(grant_table)>0){grant_table$funder <- basename(grant_table$funder)}
    grant_collapse <- grant_table[,lapply(.SD,paste,collapse = ';'),.SDcols = names(grant_table)]
    work_dt <- cbind(base_info,bib_info,open_access,source_info,author_collapse, grant_collapse)
  }
  citation_returns <- c('author_display_name','publication_year','title','source.display_name','bib_info','doi')
  if(data_style=='citation'){return(work_dt[,colnames(work_dt) %in% citation_returns,with = F])}
  if(data_style=='comprehensive'){return(work_dt)}
}

#' Vectorized processing of work json data
#'
#' @description Same function but can take a list of works. Not advisable for large data sets, parallelize queryOpenAlex instead.
#' @param work a list of works results
#' @param data_style = c('bare_bones','citation','comprehensive','all')
#' @export
processWorks <- Vectorize(processWork,vectorize.args = 'work',SIMPLIFY = F,USE.NAMES = T)


